package msu.edu.msuexplorer;

import androidx.appcompat.app.AppCompatActivity;

import android.content.Intent;
import android.graphics.Typeface;
import android.os.Bundle;
import android.view.Gravity;
import android.view.View;
import android.widget.LinearLayout;
import android.widget.TableRow;
import android.widget.TextView;

public class ProfileActivity extends AppCompatActivity {

    // The user database from Firebase
    appUser firebaseDB;

    // The user's email address
    String user_email;

    // The user id generated by the database
    String uid;

    // The users username
    String username;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_profile);

        firebaseDB = appUser.getInstance();
        user_email = firebaseDB.getEmail();
        uid = firebaseDB.getUid();
        username = firebaseDB.getUsername();

        DisplayUserInfo(199, username, uid, user_email);
    }

    /**
     * Take user back to menu activity
     * @param view The view
     */
    public void onBack(View view) {
        Intent intent = new Intent(this, MenuActivity.class);
        startActivity(intent);
    }

    /**
     * Takes user back to the login page and log out
     * @param view The view
     */
    public void onSignOut(View view) {
        Intent intent = new Intent(this, LoginActivity.class);
        startActivity(intent);
        firebaseDB.LogOut();
    }

    /**
     * Display user information from the database
     *
     * @param displayName The user's display name
     * @param email User email
     * @param score The total accumulated score of the user
     * @param userId The assigned user id from the Firebase DB
     */
    public void DisplayUserInfo(int score, String displayName, String userId, String email) {
        // Get the layouts
        LinearLayout scoreLayout = findViewById(R.id.ScoreLayout);
        TableRow nameLayout = findViewById(R.id.NameRow);
        TableRow uidLayout = findViewById(R.id.IDRow);
        TableRow emailLayout = findViewById(R.id.EmailRow);

        // Layout Params
        TableRow.LayoutParams layoutParams = new TableRow.LayoutParams(
                TableRow.LayoutParams.WRAP_CONTENT,
                TableRow.LayoutParams.WRAP_CONTENT
        );
        layoutParams.setMargins(10, 10, 10, 10);
        layoutParams.gravity = Gravity.CENTER;

        // Add the score to its layout
        String scoreText = Integer.toString(score);
        TextView scoreView = new TextView(this);
        scoreView.setTextSize(30);
        scoreView.setLayoutParams(layoutParams);
        scoreLayout.addView(scoreView);

        // Add the displayName to its layout
        TextView displayNameView = new TextView(this);
        displayNameView.setText(displayName);
        displayNameView.setTextSize(15);
        displayNameView.setLayoutParams(layoutParams);
        nameLayout.addView(displayNameView);

        // Add the uid to its layout
        TextView uidView = new TextView(this);
        uidView.setText(userId);
        uidView.setTextSize(15);
        uidView.setLayoutParams(layoutParams);
        uidLayout.addView(uidView);

        // Add the email to its layout
        TextView emailView = new TextView(this);
        emailView.setText(email);
        emailView.setTextSize(15);
        emailView.setLayoutParams(layoutParams);
        emailLayout.addView(emailView);
    }
}